version: "3.7"

services:
  marsserver:
    build: './marsserver'
    image: abonneau/marsserver
    ports:
      - 8080:8080
    volumes:
      - photo_cache:/photo_cache
  marsclient:
    build: './marsclient'
    image: abonneau/marsclient
    ports:
      - 80:80

volumes:
  photo_cache:

networks:
  default: